apiVersion: v1
kind: ConfigMap
metadata:
  name: go-k8s-probes
data:
  ### database
  DB_HOST: "postgresql.postgres.svc.cluster.local"
  DB_NAME: products

  ### products
  PRODUCTS_REST_HOST: "0.0.0.0"

  ### k8s-probes
  KUBE_PROBES_HOST: "0.0.0.0"

  ### monitoring
  MONITOR_HOST: "0.0.0.0"

  ### tracing (jaeger)
  JAEGER_DISABLED: true
  #JAEGER_AGENT_HOST=localhost
  #JAEGER_AGENT_PORT=6831
  #JAEGER_SAMPLER_TYPE=const # constant sampler
  #JAEGER_SAMPLER_PARAM=1 # always sampled
  #JAEGER_REPORTER_MAX_QUEUE_SIZE=0
  #JAEGER_REPORTER_LOG_SPANS=true
  #JAEGER_REPORTER_FLUSH_INTERVAL=1s
  #JAEGER_SERVICE_NAME=products-service
