
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollout

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: go-k8s-probes

commonAnnotations:
  version: "v1.0"
#  version: "v1.1"

images:
  - name: bygui86/go-k8s-probes
    newTag: v1.0
#    newTag: v1.1
